### ISSUE TITLE
Resource Bundle is not visible in Plone 5.0.2

### ISSUE THREAD

**Issue by agitator** [collective/example.p4p5#10]
... or is it only me?

**Comment by ebrehault** [comment]
Not just you, you are right.
However the tests are green, and indeed:
- If you just install the module using the Plone control panel, it does not work,
- but if you go to portal_setup and import the default profile (that's what the tests do), then it works.

So I guess QuickInstaller is not importing the default profile.

@hvelarde, @thet, any idea why?

**Comment by thet** [comment]
no... maybe @mauritsvanrees ? does quickinstaller not understand this? https://github.com/collective/example.p4p5/blob/master/src/example/p4p5/profiles.zcml#L25

**Comment by mauritsvanrees** [comment]
The quick installer sorts the profiles alphabetically and installs the first one. In this case, that is `base`.

I am changing that in plip 1340: https://github.com/plone/Products.CMFPlone/issues/1340

**Comment by ebrehault** [comment]
@mauritsvanrees wouah, tricky :), thanks!

**Comment by agitator** [comment]
argh... that one bit me again...

marking it with 
Products.CMFPlone.interfaces.INonInstallable and
Products.CMFQuickInstallerToolinterfaces.INonInstallable
helps as well

**Comment by agitator** [comment]
seems marking with ^^^ doesn't work anymore?

**Comment by ebrehault** [comment]
@agitator I am not sure I understand what you mean:
you have tried to fix the problem using INonInstallable but it does not work?
but what about the fix I pushed yesterday (rename base into install-base so default gets first in alphabetical order)?

**Comment by agitator** [comment]
renaming works for sure

just checked what worked before (alpinecitysprint) on https://github.com/collective/sc.social.like/blob/plone5/sc/social/like/profiles.zcml

seems hiding the profile doesn't work anymore ...?

**Comment by mauritsvanrees** [comment]
You have got these two:

```
Products.CMFQuickInstallerTool.interfaces.INonInstallable:

      def getNonInstallableProducts(self):
          # Make sure this package does not show up in the add-ons
          # control panel:
          return ['collective.hidden.package']

Products.CMFPlone.interfaces.INonInstallable:

      def getNonInstallableProfiles(self):
          # Hide the base profile from your.package from the list
          # shown at site creation.
          return ['your.package:base']
```

Note the different method names.
With the one from QI you prevent a package from showing up in the add-ons control panel.
With the one from Plone you prevent a profile from showing up in some profile lists.

The non installable profiles have no effect on which profile is used as the profile when installing a package.

In #1340 I am changing that. Hidden profiles will not be chosen as the installation profile, unless no other profile can be found (that might warrant a warning). And I am combining the two into the INonInstallable interface from Plone: it can have both `getNonInstallableProducts` and `getNonInstallableProfiles`, with their original meanings.

**Comment by agitator** [comment]
somehow had the impression the hide solved the problem at alpinecitysprint
nice that you're changing that :-)
