### ISSUE TITLE
Is confusing to have so many profiles

### ISSUE THREAD

**Issue by hvelarde** [collective/example.p4p5#6]
Package must show only the installation profile:

![selecao_008](https://cloud.githubusercontent.com/assets/341393/12550341/4b87e17e-c34a-11e5-82b2-9af2c4d5bca2.png)

**Comment by ebrehault** [comment]
Yes it would be nice.
Do you know how we can fix that?

Note: for the record, the add-on installation at site creation time is not recommended (it might produce bad side-effects as far as I know).

**Comment by hvelarde** [comment]
never heard of one, we always use that without any issues; I will do some work to fix this, hold on.
